### ISSUE TITLE
FEATURE - Scroll from bottom to top when clicking on Button (Facing An Issue?)

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [ashutoshgithubs/iemhacks_DEV-G#40]
Scroll the page to bottom then click the Facing an Issue button then  except showing the contact component it is showing the same Footer not showing the new Content i.e Contact Component
If it is a correct feature then i want to work on this under GSSOC 2024 .

https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/118350936/4304202a-7d0b-4a6d-9a56-0f349aef93ec

**Comment by ashutoshgithubs** [comment]
Hi @Ayushmaanagarwal1211 , The main aim of this button is to navigate you from anywhere to Contact page. As you scrolled down to footer part then you clicked that button. Route is changed to Contact. As footer is attached to all pages that's why you are seeing the footer from bottom. Its not an issue. 
But thanks for exploring the website. If you find any other issue/bugs/feature enhancement, please raised it under issue section.

**Comment by Ayushmaanagarwal1211** [comment]
Ok .
